export const oxygen = [
    'Oxygen Concentrators',
    'Oxygen Cylinders',
    'Oxygen Corona Virus',
    'Oxygen rocket repellant',
    'Oxygen sewage treatment',
];

export const virtualReality = [
    'virtual reality multimedia',
    'virtual reality movies',
    'virtual reality education',
    'virtual reality healthcare',
    'virtual reality gaming',
];

export const robotics = [
    'robotics healthcare',
    'robotics agriculture',
    'robotics education',
    'robotics AI',
    'robotics hotel '
]

export const covid = [
   { checked : false,serialNo: 1,publicationNumber: 'CN111588720A', title: 'application of atorvastatin calcium in preparation of drugs for treating COVID-19' , dwpiTitle : 'Application of (R-(R,R))-2-(4-fluorophenyl)-beta,beta-dihydroxy-5-(1-methylethyl)-3-phenyl-4-((aniline)carbonyl)-1H-pyrrole-1-heptanoic acid calcium trihydrate compound for preparing drugs for treating coronary pneumonia'},
   { checked : false,serialNo: 2,publicationNumber: 'CN111603465A', title: 'Application of lovastatin in preparation of medicine for treating new coronal pneumonia' , dwpiTitle : 'Use of lovastatin for preparation drugs for treating new coronary pneumonia'},
   { checked : false,serialNo: 3,publicationNumber: 'CN111588719A', title: 'Application of simvastatin in preparation of novel coronavirus pneumonia treating drugs' , dwpiTitle : 'Use of simvastatin in preparing medicine for treating new coronary pneumonia'},
   { checked : false,serialNo: 4,publicationNumber: 'US20200357271A1', title: 'METHOD AND APPARATUS FOR ACTUATING A PUSH-TO-WALK BUTTON' , dwpiTitle : 'Hands-free method for actuating push-to-walk button, involves receiving force upon pedal proximate to base of pole and mechanically conveying force to perimeter in first cam, which is then imparted to second cam to press push-to-walk switch'},
   { checked : false,serialNo: 5,publicationNumber: 'CN111154923A', title: 'Primer for amplifying nucleotide fragment of SARS-CoV-2 gene and application of primer' , dwpiTitle : 'New primer used for preparing kit such as qualitative detection kit, semi-quantitative detection kit or quantitative detection kit and fluorescence quantitative detection kit for detecting coronavirus, comprises specific base pair sequence'},
   { checked : false,serialNo: 6,publicationNumber: 'US20200390177A1', title: 'HEADWEAR WITH INTEGRATED FACECOVER' , dwpiTitle : 'Headwear e.g. baseball cap has elastic band that is configured to secure deployable face mask to user and is attached to deployable face mask and configured to be secured with fastener around back portion of user head or neck'},
   { checked : false,serialNo: 7,publicationNumber: 'CN111423508A', title: 'Isolated SARS-CoV-2 protein binding molecule against virus infection' , dwpiTitle : 'New isolated severe acute respiratory syndrome coronavirus protein binding molecule against viral infection useful e.g. for preparing composition or detecting product, comprising e.g. heavy chain and light chain variable region'},
   { checked : false,serialNo: 8,publicationNumber: 'CN111430023A', title: 'Remote intelligent cun-guan-chi pulse diagnosis apparatus' , dwpiTitle : 'Remote intelligent inch ruler pulse diagnosis device, has consultation terminal provided with impulse terminal and connected with virtual reality hardware technology device for determining desired data'},
   { checked : false,serialNo: 9,publicationNumber: 'KR202101034U', title: 'Mask and that adheres to the face' , dwpiTitle : 'Facial contact mask has hook strap that is installed through side portion so that first through hole moves along hook strap, where hook strap is not removed from first through hole, by installing hook strap through first through hole'},
   { checked : false,serialNo: 10,publicationNumber: 'FR3022182B1', title: 'Method for production of multi-layer data medium in official document, involves performing marking lamination on layer covered with marking films, and separating marking films from layer that presents security inscriptions', dwpiTitle : 'Device for detecting/monitoring a physiological condition/biological phenomena comprises needle assembly having a needle body with radiation ports, electromagnetic radiation carrier, radiation source and electromagnetic radiation detector'},
 ];
 export const machineLearning = [
   {checked : false, serialNo: 1,publicationNumber: 'EP3665687A2', title: 'DNA REPAIR PROFILING AND METHODS THEREFOR' , dwpiTitle : 'Method of analyzing omics data of DNA repair, involves associating omics data with one of health status, omics error status, age, disease, prophylactic recommendation and therapeutic recommendation'},
   {checked : false, serialNo: 2,publicationNumber: 'CN112446298A', title: 'Hyperspectral nondestructive testing method for wheat scab' , dwpiTitle : 'High-spectrum non-destructive detection method for wheat scab, involves comparing and analyzing recognition accuracy of model through test set to obtain optimal wheat grain scab identification model, detecting situation of wheat head blight'},
   {checked : false, serialNo: 3,publicationNumber: 'CN112672048A', title: 'Image processing method based on binocular image and neural network algorithm' , dwpiTitle : 'Image processing method based on binocular images and neural network algorithms, involves extracting target contour to obtain foreground map and synthesizing foreground image and background image to obtain final effect image'},
   {checked : false, serialNo: 4,publicationNumber: 'CN112579389A', title: 'Method and system with fault detection and autonomous control functions' , dwpiTitle : 'Air-conditioning equipment fault detection and autonomous controlling method, involves giving latest control instructions to corresponding air-conditioning equipment to control air-conditioning equipment through deep learning analysis'},
   {checked : false, serialNo: 5,publicationNumber: 'CN112749635A', title: 'Cross-subject EEG cognitive state recognition method based on prototype clustering domain adaptation algorithm' , dwpiTitle : 'Cross-subject EEG cognitive state recognition method based on prototype clustering domain adaptive algorithm, involves collecting EEG data of multiple clinical network game patients meeting experimental condition under induced task'},
   {checked : false, serialNo: 6,publicationNumber: 'CN112715020A', title: 'Selecting an electronic message in a computing system' , dwpiTitle : 'Method for selectively surfacing email messages in computing systems, involves transmitting incoming email with modified metadata to client device through computer network to user in section of inbox in email client on client device'},
   {checked : false, serialNo: 7,publicationNumber: 'US10885053B2', title: 'Systems and methods for dynamically rendering data lineage' , dwpiTitle : 'New isolated severe acute respiratory syndrome coronavirus protein binding molecule against viral infection useful e.g. for preparing composition or detecting product, comprising e.g. heavy chain and light chain variable region'},
   {checked : false, serialNo: 8,publicationNumber: 'US10893330B2', title: 'Concurrent presentation of non-programming media assets with programming media content at client device' , dwpiTitle : 'Remote intelligent inch ruler pulse diagnosis device, has consultation terminal provided with impulse terminal and connected with virtual reality hardware technology device for determining desired data'},
   {checked : false, serialNo: 9,publicationNumber: 'EP3757548A1', title: 'REFLECTION CHARACTERISTIC MEASUREMENT DEVICE, CORRESPONDING METHOD AND NON-TRANSITORY STORAGE MEDIUM' , dwpiTitle : 'Facial contact mask has hook strap that is installed through side portion so that first through hole moves along hook strap, where hook strap is not removed from first through hole, by installing hook strap through first through hole'},
   {checked : false, serialNo: 10,publicationNumber: 'EP3740881A1', title: 'CONTEXT-SENSITIVE METHODS OF SURFACING COMPREHENSIVE KNOWLEDGE IN AND BETWEEN APPLICATIONS', dwpiTitle : 'Device for detecting/monitoring a physiological condition/biological phenomena comprises needle assembly having a needle body with radiation ports, electromagnetic radiation carrier, radiation source and electromagnetic radiation detector'},
 ];
 
export const fiveG = [
   { checked : false,serialNo: 1,publicationNumber: 'US10973979B2', title: 'Blood glucose control system with control parameter modification' , dwpiTitle : 'Device for detecting/monitoring a physiological condition/biological phenomena comprises needle assembly having a needle body with radiation ports, electromagnetic radiation carrier, radiation source and electromagnetic radiation detector'},
   { checked : false,serialNo: 2,publicationNumber: 'US10966233B2', title: 'Methods and devices for information transmission' , dwpiTitle : 'Steam condensation system, has recoverer connected with heating device, where heating device and recoverer are provided with press, and recoverer is connected with self-control box and provided with pressure gauge and temperature gauge'},
   { checked : false,serialNo: 3,publicationNumber: 'US10944509B2', title: 'Method to generate ordered sequence for polar codes' , dwpiTitle : 'Breathing apparatus supplying oxygen has mask, air conduits and breathing bag in form of oxygen generator including light impenetrable and penetrable shells'},
   { checked : false,serialNo: 4,publicationNumber: 'US10966975B2', title: 'Smart broadcast device' , dwpiTitle : 'Device for detecting/monitoring a physiological condition/biological phenomena comprises needle assembly having a needle body with radiation ports, electromagnetic radiation carrier, radiation source and electromagnetic radiation detector'},
   { checked : false,serialNo: 5,publicationNumber: 'US10923819B2', title: 'Antenna system and terminal' , dwpiTitle : 'Steam condensation system, has recoverer connected with heating device, where heating device and recoverer are provided with press, and recoverer is connected with self-control box and provided with pressure gauge and temperature gauge'},
   { checked : false,serialNo: 6,publicationNumber: 'US10958245B2', title: 'Acoustic filter using acoustic coupling' , dwpiTitle : 'Breathing apparatus supplying oxygen has mask, air conduits and breathing bag in form of oxygen generator including light impenetrable and penetrable shells'},
   { checked : false,serialNo: 7,publicationNumber: 'US10963452B2', title: 'Asset management method and apparatus, and electronic device' , dwpiTitle : 'Device for detecting/monitoring a physiological condition/biological phenomena comprises needle assembly having a needle body with radiation ports, electromagnetic radiation carrier, radiation source and electromagnetic radiation detector'},
   { checked : false,serialNo: 8,publicationNumber: 'US10972136B2', title: 'Polar code rate matching method and apparatus' , dwpiTitle : 'Steam condensation system, has recoverer connected with heating device, where heating device and recoverer are provided with press, and recoverer is connected with self-control box and provided with pressure gauge and temperature gauge'},
   { checked : false,serialNo: 9,publicationNumber: 'CN111208925A', title: 'Method for establishing application combination and electronic equipment' , dwpiTitle : 'Breathing apparatus supplying oxygen has mask, air conduits and breathing bag in form of oxygen generator including light impenetrable and penetrable shells'},
   { checked : false,serialNo: 10,publicationNumber: 'US10952218B2', title: 'BWP switching method and apparatus, and terminal device' , dwpiTitle : 'Breathing apparatus supplying oxygen has mask, air conduits and breathing bag in form of oxygen generator including light impenetrable and penetrable shells'},
 ];
 


export const oxygenHuman = [
    { checked : false,serialNo: 1,publicationNumber: 'WO2004026363A2', title: 'NEEDLE WITH FIBEROPTIC CAPABILITY' , dwpiTitle : 'Device for detecting/monitoring a physiological condition/biological phenomena comprises needle assembly having a needle body with radiation ports, electromagnetic radiation carrier, radiation source and electromagnetic radiation detector'},
     { checked : false, serialNo: 2,publicationNumber: 'CN103386212A', title: ' Water vapor condensation system' , dwpiTitle : 'Steam condensation system, has recoverer connected with heating device, where heating device and recoverer are provided with press, and recoverer is connected with self-control box and provided with pressure gauge and temperature gauge'},
     { checked : false,serialNo: 3,publicationNumber: 'RU2106882C1', title: 'RESPIRATOR DEVICE FOR SUPPLYING OXYGEN TO HUMAN ORGANISM ' , dwpiTitle : 'Breathing apparatus supplying oxygen has mask, air conduits and breathing bag in form of oxygen generator including light impenetrable and penetrable shells'},
     { checked : false,serialNo: 4,publicationNumber: 'IN200905726P1', title: '"DRYING AND GASIFICATION PROCESS"' , dwpiTitle : 'Syngas production from carbonaceous substance and/or carbonaceous substance treatment involves reducing surface moisture of carbonaceous substance which is directly contacted with hot gas, and/or indirectly contacting with saturated steam'},
     {checked : false, serialNo: 5,publicationNumber: 'IN199700521I1', title: ' LARGE CAPACITY VACUUM PRESSURE SWING ADSORPTION PROCESS AND SYSTEM' , dwpiTitle : 'Single bed pressure swing adsorption process recovering oxygen@ from air by reducing differential pressure across a compressor used in the improved single bed process, reducing operating cycle times, and giving higher efficiency'},
     { checked : false,serialNo: 6,publicationNumber: 'IN211080BIN211080B', title: 'METHOD AND APPARATUS FOR BACKING-UP OXY-FUEL COMBUSTION WITH AIR-FUEL COMBUSTION' , dwpiTitle : 'Back up device for oxy-fuel burner used in e.g. industrial glass melting furnaces comprises air-fuel burner'},
     { checked : false,serialNo: 7,publicationNumber: 'IN200905726P1', title: '"DRYING AND GASIFICATION PROCESS"' , dwpiTitle : 'Syngas production from carbonaceous substance and/or carbonaceous substance treatment involves reducing surface moisture of carbonaceous substance which is directly contacted with hot gas, and/or indirectly contacting with saturated steam'},
     {checked : false, serialNo: 8,publicationNumber: 'IN199700521I1', title: ' LARGE CAPACITY VACUUM PRESSURE SWING ADSORPTION PROCESS AND SYSTEM' , dwpiTitle : 'Single bed pressure swing adsorption process recovering oxygen@ from air by reducing differential pressure across a compressor used in the improved single bed process, reducing operating cycle times, and giving higher efficiency'},
     { checked : false,serialNo: 9,publicationNumber: 'IN211080BIN211080B', title: 'METHOD AND APPARATUS FOR BACKING-UP OXY-FUEL COMBUSTION WITH AIR-FUEL COMBUSTION' , dwpiTitle : 'Back up device for oxy-fuel burner used in e.g. industrial glass melting furnaces comprises air-fuel burner'},
  ];
  
  export const oxygenCorona = [
    { checked : false,serialNo: 1,publicationNumber: 'US6290801B1', title: 'Cold seal package and method for making the same' , dwpiTitle : 'Cold seal package including two substrates sealed together by a non resealable seal'},
     {checked : false, serialNo: 2,publicationNumber: 'EP3810425A1', title: ' METHODS OF FORMING CONTACT LENSES TO CONTAIN BIOACTIVE AGENTS' , dwpiTitle : 'Method for forming and/or using contact lens, involves pad printing bioactive agents to form layer, and curing layer to form portion of contact lens, and forming contact lens so that layer of agents is fixed within interior of lens'},
     { checked : false,serialNo: 3,publicationNumber: 'CA2224856C', title: 'SURFACE MODIFICATION OF POLYMERS AND CARBON-BASED MATERIALS' , dwpiTitle : 'Polymeric material having a thin surface layer enriched with silicon comprises material modified chemically for gradation of layers through to unmodified material, useful for water resistant package or textile'},
     { checked : false,serialNo: 4,publicationNumber: 'IN200905726P1', title: '"DRYING AND GASIFICATION PROCESS"' , dwpiTitle : 'Syngas production from carbonaceous substance and/or carbonaceous substance treatment involves reducing surface moisture of carbonaceous substance which is directly contacted with hot gas, and/or indirectly contacting with saturated steam'},
     {checked : false, serialNo: 5,publicationNumber: 'IN199700521I1', title: ' LARGE CAPACITY VACUUM PRESSURE SWING ADSORPTION PROCESS AND SYSTEM' , dwpiTitle : 'Single bed pressure swing adsorption process recovering oxygen@ from air by reducing differential pressure across a compressor used in the improved single bed process, reducing operating cycle times, and giving higher efficiency'},
     { checked : false,serialNo: 6,publicationNumber: 'IN211080BIN211080B', title: 'METHOD AND APPARATUS FOR BACKING-UP OXY-FUEL COMBUSTION WITH AIR-FUEL COMBUSTION' , dwpiTitle : 'Back up device for oxy-fuel burner used in e.g. industrial glass melting furnaces comprises air-fuel burner'},
     { checked : false,serialNo: 7,publicationNumber: 'IN200905726P1', title: '"DRYING AND GASIFICATION PROCESS"' , dwpiTitle : 'Syngas production from carbonaceous substance and/or carbonaceous substance treatment involves reducing surface moisture of carbonaceous substance which is directly contacted with hot gas, and/or indirectly contacting with saturated steam'},
     {checked : false, serialNo: 8,publicationNumber: 'IN199700521I1', title: ' LARGE CAPACITY VACUUM PRESSURE SWING ADSORPTION PROCESS AND SYSTEM' , dwpiTitle : 'Single bed pressure swing adsorption process recovering oxygen@ from air by reducing differential pressure across a compressor used in the improved single bed process, reducing operating cycle times, and giving higher efficiency'},
     { checked : false,serialNo: 9,publicationNumber: 'IN211080BIN211080B', title: 'METHOD AND APPARATUS FOR BACKING-UP OXY-FUEL COMBUSTION WITH AIR-FUEL COMBUSTION' , dwpiTitle : 'Back up device for oxy-fuel burner used in e.g. industrial glass melting furnaces comprises air-fuel burner'},
  ];
  
  export const oxygenPlants = [
    { checked : false,serialNo: 1,publicationNumber: 'IN200905726P1', title: '"DRYING AND GASIFICATION PROCESS"' , dwpiTitle : 'Syngas production from carbonaceous substance and/or carbonaceous substance treatment involves reducing surface moisture of carbonaceous substance which is directly contacted with hot gas, and/or indirectly contacting with saturated steam'},
     {checked : false, serialNo: 2,publicationNumber: 'IN199700521I1', title: ' LARGE CAPACITY VACUUM PRESSURE SWING ADSORPTION PROCESS AND SYSTEM' , dwpiTitle : 'Single bed pressure swing adsorption process recovering oxygen@ from air by reducing differential pressure across a compressor used in the improved single bed process, reducing operating cycle times, and giving higher efficiency'},
     { checked : false,serialNo: 3,publicationNumber: 'IN211080BIN211080B', title: 'METHOD AND APPARATUS FOR BACKING-UP OXY-FUEL COMBUSTION WITH AIR-FUEL COMBUSTION' , dwpiTitle : 'Back up device for oxy-fuel burner used in e.g. industrial glass melting furnaces comprises air-fuel burner'},
     { checked : false,serialNo: 4,publicationNumber: 'RU1612396C', title: 'MINIATURE PULMONARY AUTOMATE' , dwpiTitle : 'Small-size breathing apparatus incorporates rigid spring loaded membrane to cover by-pass channel nozzle'},
     { checked : false,serialNo: 5,publicationNumber: 'CN201088759Y', title: 'Artificial respiration oxygen booster for rescuing infectious patient' , dwpiTitle : 'Artificial respiration oxygen enriching apparatus for use in infectious patients rescuing process, has inlet oxygen pipe with valve immovably connected with rescue breathing pipe, and round ceil fixed on rescue breathing pipe'},
     { checked : false,serialNo: 6,publicationNumber: 'CN201123315Y', title: 'Simple oxygenation machine' , dwpiTitle : 'Simple oxygenator useful for industrial applications, comprises upper oxygen transfer bottle, lower oxygen transfer bottle, water conduit, and oxygen conduit'},
     {checked : false, serialNo: 7,publicationNumber: 'JP1133906A', title: 'PRODUCTION OF OXIDE SUPERCONDUCTOR' , dwpiTitle : 'Oxide superconductor prodn. by treating precursor of oxide superconductor structural element in oxidising atmos., and reducing in hydrogen atmos.'},
     {checked : false, serialNo: 8,publicationNumber: 'JP1124917A', title: ' MANUFACTURE OF WIRE MATERIAL' , dwpiTitle : 'Mfg. superconducting wire material with small defect and distortion using powder made by fusion spray as superconductor powder which is filled in reinforcing pipe and drawn NoAbstract'},
     { checked : false,serialNo: 9,publicationNumber: 'JP1122957A', title: 'PRODUCTION OF OXIDE SUPERCONDUCTOR	 ' , dwpiTitle : 'Mfg. superconducting oxide from powder contg. Gp=IIa, Gp=IIa, Gp=Ib elements also Gp=VIb element, etc. and to which titania is added before sintering'},
     ];
  
  export const oxygenAtmosphere = [
    {checked : false, serialNo: 1,publicationNumber: 'JP1133906A', title: 'PRODUCTION OF OXIDE SUPERCONDUCTOR' , dwpiTitle : 'Oxide superconductor prodn. by treating precursor of oxide superconductor structural element in oxidising atmos., and reducing in hydrogen atmos.'},
     {checked : false, serialNo: 2,publicationNumber: 'JP1124917A', title: ' MANUFACTURE OF WIRE MATERIAL' , dwpiTitle : 'Mfg. superconducting wire material with small defect and distortion using powder made by fusion spray as superconductor powder which is filled in reinforcing pipe and drawn NoAbstract'},
     { checked : false,serialNo: 3,publicationNumber: 'JP1122957A', title: 'PRODUCTION OF OXIDE SUPERCONDUCTOR	 ' , dwpiTitle : 'Mfg. superconducting oxide from powder contg. Gp=IIa, Gp=IIa, Gp=Ib elements also Gp=VIb element, etc. and to which titania is added before sintering'},
     { checked : false,serialNo: 4,publicationNumber: 'RU1612396C', title: 'MINIATURE PULMONARY AUTOMATE' , dwpiTitle : 'Small-size breathing apparatus incorporates rigid spring loaded membrane to cover by-pass channel nozzle'},
     { checked : false,serialNo: 5,publicationNumber: 'CN201088759Y', title: 'Artificial respiration oxygen booster for rescuing infectious patient' , dwpiTitle : 'Artificial respiration oxygen enriching apparatus for use in infectious patients rescuing process, has inlet oxygen pipe with valve immovably connected with rescue breathing pipe, and round ceil fixed on rescue breathing pipe'},
     { checked : false,serialNo: 6,publicationNumber: 'CN201123315Y', title: 'Simple oxygenation machine' , dwpiTitle : 'Simple oxygenator useful for industrial applications, comprises upper oxygen transfer bottle, lower oxygen transfer bottle, water conduit, and oxygen conduit'},
     { checked : false,serialNo: 7,publicationNumber: 'IN200905726P1', title: '"DRYING AND GASIFICATION PROCESS"' , dwpiTitle : 'Syngas production from carbonaceous substance and/or carbonaceous substance treatment involves reducing surface moisture of carbonaceous substance which is directly contacted with hot gas, and/or indirectly contacting with saturated steam'},
     {checked : false, serialNo: 8,publicationNumber: 'IN199700521I1', title: ' LARGE CAPACITY VACUUM PRESSURE SWING ADSORPTION PROCESS AND SYSTEM' , dwpiTitle : 'Single bed pressure swing adsorption process recovering oxygen@ from air by reducing differential pressure across a compressor used in the improved single bed process, reducing operating cycle times, and giving higher efficiency'},
     { checked : false,serialNo: 9,publicationNumber: 'IN211080BIN211080B', title: 'METHOD AND APPARATUS FOR BACKING-UP OXY-FUEL COMBUSTION WITH AIR-FUEL COMBUSTION' , dwpiTitle : 'Back up device for oxy-fuel burner used in e.g. industrial glass melting furnaces comprises air-fuel burner'},
     ];
  
  export const oxygenMachine = [
    { checked : false,serialNo: 1,publicationNumber: 'RU1612396C', title: 'MINIATURE PULMONARY AUTOMATE' , dwpiTitle : 'Small-size breathing apparatus incorporates rigid spring loaded membrane to cover by-pass channel nozzle'},
     { checked : false,serialNo: 2,publicationNumber: 'CN201088759Y', title: 'Artificial respiration oxygen booster for rescuing infectious patient' , dwpiTitle : 'Artificial respiration oxygen enriching apparatus for use in infectious patients rescuing process, has inlet oxygen pipe with valve immovably connected with rescue breathing pipe, and round ceil fixed on rescue breathing pipe'},
     { checked : false,serialNo: 3,publicationNumber: 'CN201123315Y', title: 'Simple oxygenation machine' , dwpiTitle : 'Simple oxygenator useful for industrial applications, comprises upper oxygen transfer bottle, lower oxygen transfer bottle, water conduit, and oxygen conduit'},
     {checked : false, serialNo: 4,publicationNumber: 'JP1133906A', title: 'PRODUCTION OF OXIDE SUPERCONDUCTOR' , dwpiTitle : 'Oxide superconductor prodn. by treating precursor of oxide superconductor structural element in oxidising atmos., and reducing in hydrogen atmos.'},
     {checked : false, serialNo: 5,publicationNumber: 'JP1124917A', title: ' MANUFACTURE OF WIRE MATERIAL' , dwpiTitle : 'Mfg. superconducting wire material with small defect and distortion using powder made by fusion spray as superconductor powder which is filled in reinforcing pipe and drawn NoAbstract'},
     { checked : false,serialNo: 6,publicationNumber: 'JP1122957A', title: 'PRODUCTION OF OXIDE SUPERCONDUCTOR	 ' , dwpiTitle : 'Mfg. superconducting oxide from powder contg. Gp=IIa, Gp=IIa, Gp=Ib elements also Gp=VIb element, etc. and to which titania is added before sintering'},
     { checked : false, serialNo: 7,publicationNumber: 'CN103386212A', title: ' Water vapor condensation system' , dwpiTitle : 'Steam condensation system, has recoverer connected with heating device, where heating device and recoverer are provided with press, and recoverer is connected with self-control box and provided with pressure gauge and temperature gauge'},
     { checked : false,serialNo: 8,publicationNumber: 'RU2106882C1', title: 'RESPIRATOR DEVICE FOR SUPPLYING OXYGEN TO HUMAN ORGANISM ' , dwpiTitle : 'Breathing apparatus supplying oxygen has mask, air conduits and breathing bag in form of oxygen generator including light impenetrable and penetrable shells'},
     { checked : false,serialNo: 9,publicationNumber: 'IN200905726P1', title: '"DRYING AND GASIFICATION PROCESS"' , dwpiTitle : 'Syngas production from carbonaceous substance and/or carbonaceous substance treatment involves reducing surface moisture of carbonaceous substance which is directly contacted with hot gas, and/or indirectly contacting with saturated steam'},
  ];
  
  
  
  export const vrMultiMedia = [
    {checked : false, serialNo: 1,publicationNumber: 'US20150193770A1', title: 'Systems, methods and devices for trusted transactions' , dwpiTitle : 'Trusted transaction method in on-line environment, involves verifying, authenticating and authorizing digitally sampled information for approval with approval element selected from preset key, message and cipher'},
     {checked : false, serialNo: 2,publicationNumber: 'IN225238B', title: 'A GAMING-JURISDICTION-AUTHORIZED SECURE GAMING-BUSINESS DATA DISTRIBUTION METHOD AND SYSTEM.' , dwpiTitle : 'Legally-authorized virtual distributed interactive casino gaming system includes remote player station to enable player to place wager on casino games'},
     { checked : false,serialNo: 3,publicationNumber: 'CN108282494A', title: 'Virtual reality multimedia data encryption transmitter' , dwpiTitle : 'Virtual reality multimedia data encryption transmitter has encrypted transmitting unit whose lower surface is connected to one side of upper surface of virtual reality glasses, and headband that is provided on both sides of glasses'},
     {checked : false, serialNo: 4,publicationNumber: 'EP3713256A1', title: 'SOUND PROCESSING SYSTEM OF AMBISONIC FORMAT AND SOUND PROCESSING METHOD OF AMBISONIC FORMAT' , dwpiTitle : 'Sound processing system for ambisonic format, has processor that is configured to apply space transfer function to first audio data and generate sound output generated corresponding to second position'},
     { checked : false,serialNo: 5,publicationNumber: 'US20170301142A1', title: 'TRANSITIONING FROM A DIGITAL GRAPHICAL APPLICATION TO AN APPLICATION INSTALL' , dwpiTitle : 'Client computing device for transitioning from digital graphical environment to application download environment, has processors for executing marketplace application on device and navigating to additional content on marketplace application'},
     { checked : false,serialNo: 6,publicationNumber: 'US20050244804A1', title: 'Process of relaying a story having a unique plot' , dwpiTitle : 'Story relaying method involves creating video representation of actor, having timeline and unique plot indicating active participation of character in all events during unconscious time period'},
     { checked : false,serialNo: 7,publicationNumber: 'KR2020069800A', title: 'Employment consignment management system for persons with disabilities' , dwpiTitle : 'Employment consignment management method for person with disability i.e. hearing impaired people, comprises repetitive education step of performing repetitive education through virtual reality for part requiring re-education'},
     { checked : false,serialNo: 8,publicationNumber: 'US20090098524A1', title: 'Internet-based Pedagogical and Andragogical Method and System Using Virtual Reality' , dwpiTitle : '1 of Online participants e.g. child, interaction facilitating system i.e. real life virtual education immersion system, for use in education community, has software for providing unit to administer financial records of users'},
     { checked : false,serialNo: 9,publicationNumber: 'CN105825059A', title: 'Method for researching SPH (Smoothed Particle Hydrodynamics) multi-phase flow haptic interaction' , dwpiTitle : 'Method for performing multi-phase flow tactile interaction research of SPH, involves updating rotating angle speed of rotary component of haptic device for obtaining low and high contact frequency of finite impulse response filter'},
     ];
  
  export const vrMovies = [
    {checked : false, serialNo: 1,publicationNumber: 'EP3713256A1', title: 'SOUND PROCESSING SYSTEM OF AMBISONIC FORMAT AND SOUND PROCESSING METHOD OF AMBISONIC FORMAT' , dwpiTitle : 'Sound processing system for ambisonic format, has processor that is configured to apply space transfer function to first audio data and generate sound output generated corresponding to second position'},
     { checked : false,serialNo: 2,publicationNumber: 'US20170301142A1', title: 'TRANSITIONING FROM A DIGITAL GRAPHICAL APPLICATION TO AN APPLICATION INSTALL' , dwpiTitle : 'Client computing device for transitioning from digital graphical environment to application download environment, has processors for executing marketplace application on device and navigating to additional content on marketplace application'},
     { checked : false,serialNo: 3,publicationNumber: 'US20050244804A1', title: 'Process of relaying a story having a unique plot' , dwpiTitle : 'Story relaying method involves creating video representation of actor, having timeline and unique plot indicating active participation of character in all events during unconscious time period'},
     { checked : false,serialNo: 4,publicationNumber: 'KR2020069800A', title: 'Employment consignment management system for persons with disabilities' , dwpiTitle : 'Employment consignment management method for person with disability i.e. hearing impaired people, comprises repetitive education step of performing repetitive education through virtual reality for part requiring re-education'},
     { checked : false,serialNo: 5,publicationNumber: 'US20090098524A1', title: 'Internet-based Pedagogical and Andragogical Method and System Using Virtual Reality' , dwpiTitle : '1 of Online participants e.g. child, interaction facilitating system i.e. real life virtual education immersion system, for use in education community, has software for providing unit to administer financial records of users'},
     { checked : false,serialNo: 6,publicationNumber: 'CN105825059A', title: 'Method for researching SPH (Smoothed Particle Hydrodynamics) multi-phase flow haptic interaction' , dwpiTitle : 'Method for performing multi-phase flow tactile interaction research of SPH, involves updating rotating angle speed of rotary component of haptic device for obtaining low and high contact frequency of finite impulse response filter'},
     { checked : false,serialNo: 7,publicationNumber: 'EP3598273A1', title: 'ADAPTIVE HAPTIC EFFECT RENDERING BASED ON DYNAMIC SYSTEM IDENTIFICATION' , dwpiTitle : 'Method for generating haptic effect by haptic enabled apparatus, involves generating modified haptic signal based on parameters, and applying modified haptic signal to haptic actuator for providing haptic effect adapted to dynamic system'},
     {checked : false, serialNo: 8,publicationNumber: 'US10758824B1', title: '	Collision avoidance system for room scale virtual reality system' , dwpiTitle : '-'},
     { checked : false,serialNo: 9,publicationNumber: 'RU2018128778A', title: 'PROTECTED AUTHENTICATION USING BIOMETRIC INPUT DATA' , dwpiTitle : 'Method for securing authentication in computing device e.g. mobile phone, involves converting inputs into numeric value, and authorizing user based on numeric value of inputs'},
  ];
  
  export const vrEducation = [
    { checked : false,serialNo: 1,publicationNumber: 'KR2020069800A', title: 'Employment consignment management system for persons with disabilities' , dwpiTitle : 'Employment consignment management method for person with disability i.e. hearing impaired people, comprises repetitive education step of performing repetitive education through virtual reality for part requiring re-education'},
     { checked : false,serialNo: 2,publicationNumber: 'US20090098524A1', title: 'Internet-based Pedagogical and Andragogical Method and System Using Virtual Reality' , dwpiTitle : '1 of Online participants e.g. child, interaction facilitating system i.e. real life virtual education immersion system, for use in education community, has software for providing unit to administer financial records of users'},
     { checked : false,serialNo: 3,publicationNumber: 'CN105825059A', title: 'Method for researching SPH (Smoothed Particle Hydrodynamics) multi-phase flow haptic interaction' , dwpiTitle : 'Method for performing multi-phase flow tactile interaction research of SPH, involves updating rotating angle speed of rotary component of haptic device for obtaining low and high contact frequency of finite impulse response filter'},
     {checked : false, serialNo: 4,publicationNumber: 'EP3713256A1', title: 'SOUND PROCESSING SYSTEM OF AMBISONIC FORMAT AND SOUND PROCESSING METHOD OF AMBISONIC FORMAT' , dwpiTitle : 'Sound processing system for ambisonic format, has processor that is configured to apply space transfer function to first audio data and generate sound output generated corresponding to second position'},
     { checked : false,serialNo: 5,publicationNumber: 'US20170301142A1', title: 'TRANSITIONING FROM A DIGITAL GRAPHICAL APPLICATION TO AN APPLICATION INSTALL' , dwpiTitle : 'Client computing device for transitioning from digital graphical environment to application download environment, has processors for executing marketplace application on device and navigating to additional content on marketplace application'},
     { checked : false,serialNo: 6,publicationNumber: 'US20050244804A1', title: 'Process of relaying a story having a unique plot' , dwpiTitle : 'Story relaying method involves creating video representation of actor, having timeline and unique plot indicating active participation of character in all events during unconscious time period'},
     { checked : false,serialNo: 7,publicationNumber: 'EP3598273A1', title: 'ADAPTIVE HAPTIC EFFECT RENDERING BASED ON DYNAMIC SYSTEM IDENTIFICATION' , dwpiTitle : 'Method for generating haptic effect by haptic enabled apparatus, involves generating modified haptic signal based on parameters, and applying modified haptic signal to haptic actuator for providing haptic effect adapted to dynamic system'},
     {checked : false, serialNo: 8,publicationNumber: 'US10758824B1', title: '	Collision avoidance system for room scale virtual reality system' , dwpiTitle : '-'},
     { checked : false,serialNo: 9,publicationNumber: 'RU2018128778A', title: 'PROTECTED AUTHENTICATION USING BIOMETRIC INPUT DATA' , dwpiTitle : 'Method for securing authentication in computing device e.g. mobile phone, involves converting inputs into numeric value, and authorizing user based on numeric value of inputs'},
     ];
  
  export const vrHealthcare = [
    { checked : false,serialNo: 1,publicationNumber: 'DE19643000A1', title: 'Electro=optical viewing spectacles e.g. for three=dimensional images' , dwpiTitle : 'Electro=optical viewing spectacles e.g. for three=dimensional images use selective polarising filter to cut out unwanted incident and reflected stray light'},
     { checked : false,serialNo: 2,publicationNumber:'EP2551784A1', title: 'Method of controlling the display of a datasetMethod of controlling the display of a dataset' , dwpiTitle : 'Medical system selects subset of data from displayed dataset according to data priority scheme in response to reception of triggering information, and replaces displayed dataset by display of selected subset of data'},
     { checked : false,serialNo: 3,publicationNumber: 'US20170173262A1', title: 'MEDICAL SYSTEMS, DEVICES AND METHODS' , dwpiTitle : 'Medical system to handle diabetes, has one or more sensors associated with one or more actuators'},
     {checked : false, serialNo: 4,publicationNumber: 'EP3713256A1', title: 'SOUND PROCESSING SYSTEM OF AMBISONIC FORMAT AND SOUND PROCESSING METHOD OF AMBISONIC FORMAT' , dwpiTitle : 'Sound processing system for ambisonic format, has processor that is configured to apply space transfer function to first audio data and generate sound output generated corresponding to second position'},
     { checked : false,serialNo: 5,publicationNumber: 'US20170301142A1', title: 'TRANSITIONING FROM A DIGITAL GRAPHICAL APPLICATION TO AN APPLICATION INSTALL' , dwpiTitle : 'Client computing device for transitioning from digital graphical environment to application download environment, has processors for executing marketplace application on device and navigating to additional content on marketplace application'},
     { checked : false,serialNo: 6,publicationNumber: 'US20050244804A1', title: 'Process of relaying a story having a unique plot' , dwpiTitle : 'Story relaying method involves creating video representation of actor, having timeline and unique plot indicating active participation of character in all events during unconscious time period'},
     { checked : false,serialNo: 7,publicationNumber: 'KR2020069800A', title: 'Employment consignment management system for persons with disabilities' , dwpiTitle : 'Employment consignment management method for person with disability i.e. hearing impaired people, comprises repetitive education step of performing repetitive education through virtual reality for part requiring re-education'},
     { checked : false,serialNo: 8,publicationNumber: 'US20090098524A1', title: 'Internet-based Pedagogical and Andragogical Method and System Using Virtual Reality' , dwpiTitle : '1 of Online participants e.g. child, interaction facilitating system i.e. real life virtual education immersion system, for use in education community, has software for providing unit to administer financial records of users'},
     { checked : false,serialNo: 9,publicationNumber: 'CN105825059A', title: 'Method for researching SPH (Smoothed Particle Hydrodynamics) multi-phase flow haptic interaction' , dwpiTitle : 'Method for performing multi-phase flow tactile interaction research of SPH, involves updating rotating angle speed of rotary component of haptic device for obtaining low and high contact frequency of finite impulse response filter'},
     ];
  
  export const vrGaming = [
    { checked : false,serialNo: 1,publicationNumber: 'EP3598273A1', title: 'ADAPTIVE HAPTIC EFFECT RENDERING BASED ON DYNAMIC SYSTEM IDENTIFICATION' , dwpiTitle : 'Method for generating haptic effect by haptic enabled apparatus, involves generating modified haptic signal based on parameters, and applying modified haptic signal to haptic actuator for providing haptic effect adapted to dynamic system'},
     {checked : false, serialNo: 2,publicationNumber: 'US10758824B1', title: '	Collision avoidance system for room scale virtual reality system' , dwpiTitle : '-'},
     { checked : false,serialNo: 3,publicationNumber: 'RU2018128778A', title: 'PROTECTED AUTHENTICATION USING BIOMETRIC INPUT DATA' , dwpiTitle : 'Method for securing authentication in computing device e.g. mobile phone, involves converting inputs into numeric value, and authorizing user based on numeric value of inputs'},
     {checked : false, serialNo: 4,publicationNumber: 'EP3713256A1', title: 'SOUND PROCESSING SYSTEM OF AMBISONIC FORMAT AND SOUND PROCESSING METHOD OF AMBISONIC FORMAT' , dwpiTitle : 'Sound processing system for ambisonic format, has processor that is configured to apply space transfer function to first audio data and generate sound output generated corresponding to second position'},
     { checked : false,serialNo: 5,publicationNumber: 'US20170301142A1', title: 'TRANSITIONING FROM A DIGITAL GRAPHICAL APPLICATION TO AN APPLICATION INSTALL' , dwpiTitle : 'Client computing device for transitioning from digital graphical environment to application download environment, has processors for executing marketplace application on device and navigating to additional content on marketplace application'},
     { checked : false,serialNo: 6,publicationNumber: 'US20050244804A1', title: 'Process of relaying a story having a unique plot' , dwpiTitle : 'Story relaying method involves creating video representation of actor, having timeline and unique plot indicating active participation of character in all events during unconscious time period'},
     { checked : false,serialNo: 7,publicationNumber: 'KR2020069800A', title: 'Employment consignment management system for persons with disabilities' , dwpiTitle : 'Employment consignment management method for person with disability i.e. hearing impaired people, comprises repetitive education step of performing repetitive education through virtual reality for part requiring re-education'},
     { checked : false,serialNo: 8,publicationNumber: 'US20090098524A1', title: 'Internet-based Pedagogical and Andragogical Method and System Using Virtual Reality' , dwpiTitle : '1 of Online participants e.g. child, interaction facilitating system i.e. real life virtual education immersion system, for use in education community, has software for providing unit to administer financial records of users'},
     { checked : false,serialNo: 9,publicationNumber: 'CN105825059A', title: 'Method for researching SPH (Smoothed Particle Hydrodynamics) multi-phase flow haptic interaction' , dwpiTitle : 'Method for performing multi-phase flow tactile interaction research of SPH, involves updating rotating angle speed of rotary component of haptic device for obtaining low and high contact frequency of finite impulse response filter'},
     ];
  
  
  
  export const robohealth = [
    { checked : false,serialNo: 1,publicationNumber: 	'WO2005098476A1', title: 'METHOD AND APPARATUS FOR POSITION ESTIMATION USING REFLECTED LIGHT SOURCES' , dwpiTitle : 'Position estimation system for e.g. mobile autonomous robot, has signal processing unit, provided at e.g. mobile robot, which estimates the position of robot using detected reflection of projected light pattern'},
     { checked : false,serialNo: 2,publicationNumber: 'US20080183497A1', title: 'Method and apparatus for internet-based community of health experts' , dwpiTitle : 'Computer-implemented method for disseminating information e.g. results of MRI, related to particular medical patient, involves providing computer network forum to exchange information among two of patients, physician and one of specialists'},
     { checked : false,serialNo: 3,publicationNumber: 'US20150302571A1', title: 'RECOGNITION-BASED AUTHENTICATION, SYSTEMS AND METHODS' , dwpiTitle : 'Method of initiating handshake between first and second devices involves interpreting image data representative of photo of image presented on first device during handshake session to facilitate communication between devices'},
     { checked : false,serialNo: 4,publicationNumber: 'CN106600478A', title: 'Multifunctional robot system applied to hotel reception service' , dwpiTitle : 'Hotel concierge service multifunctional robot monitoring system, has moving robot body for judging whether customers transacting check-in service is present, and hotel monitoring system body for reminding user about recording process'},
     {checked : false, serialNo: 5,publicationNumber: 'CN109986575A', title: 'Hotel robot with environment monitoring function' , dwpiTitle : 'Environment monitoring function featured robot for use in hotel, has voltage monitoring device and touch screen whose output ends are connected with end of processing device, where processing device sends transmission signal to terminal'},
     { checked : false,serialNo: 6,publicationNumber: 'JP2000032140A', title: 'ROBOT HOTEL EMPLOYEE USING SPEECH RECOGNITION' , dwpiTitle : 'Automated hotel attendant using speech recognition for coordinating room-to-room calling over a telephone switching system'},
     { checked : false,serialNo: 7,publicationNumber: 'WO2016013927A1', title: 'A TRANSFORMATIVE ROBOTICS EDUCATION SYSTEM FOR IMPROVING CREATIVITY AMONG PARTICIPANTS' , dwpiTitle : 'Transformative robotics education system for facilitating creativity of participant, has first framework with application of principle of constructivism in assembling robot from robotic kit is initiated to explore constructive material'},
     {checked : false, serialNo: 8,publicationNumber: 'CN2933745Y', title: 'Stair climbing robot' , dwpiTitle : 'Ladder climbing robot has stander, driving mechanism, transmission mechanism, enclasping mechanism, creeping mechanism and control mechanism, where stander is equipped with DC electric motor and gear box, thus provides flexible operation'},
     { checked : false,serialNo: 9,publicationNumber: 'CN2936623Y', title: 'Driving mechanism and driving mechanism of crawling robot' , dwpiTitle : 'Drive mechanism and transmission mechanism of climbing robot'},
     ];
  
  export const roboAgri = [
    { checked : false,serialNo: 1,publicationNumber: 'CN108182098A', title: 'SReception language selection method, system and reception robot' , dwpiTitle : 'Method for selecting reception language of service robot, involves judging whether user speech is received or not, and identifying user classification if user speech is received, and selecting user language according to user classification'},
     { checked : false,serialNo: 2,publicationNumber: 'CN205552570U', title: 'Industrial robot welds galianconism' , dwpiTitle : 'Industrial robot welding short arm, has machinery arm whose lower end is connected with transverse plate, welding strip mutually connected with positive upper part of wire box, and machine arm provided with protection plate'},
     { checked : false,serialNo: 3,publicationNumber: 'CN205592320U', title: 'Intelligence flying robot vibration damper' , dwpiTitle : 'Intelligent flying robot vibration damping device, has bearing seat whose lower end is connected with step screw thread, and sleeve bearing transverse pipe whose left end is connected with connecting plate and screw thread regulating sleeve'},
     { checked : false,serialNo: 4,publicationNumber: 'CN106600478A', title: 'Multifunctional robot system applied to hotel reception service' , dwpiTitle : 'Hotel concierge service multifunctional robot monitoring system, has moving robot body for judging whether customers transacting check-in service is present, and hotel monitoring system body for reminding user about recording process'},
     {checked : false, serialNo: 5,publicationNumber: 'CN109986575A', title: 'Hotel robot with environment monitoring function' , dwpiTitle : 'Environment monitoring function featured robot for use in hotel, has voltage monitoring device and touch screen whose output ends are connected with end of processing device, where processing device sends transmission signal to terminal'},
     { checked : false,serialNo: 6,publicationNumber: 'JP2000032140A', title: 'ROBOT HOTEL EMPLOYEE USING SPEECH RECOGNITION' , dwpiTitle : 'Automated hotel attendant using speech recognition for coordinating room-to-room calling over a telephone switching system'},
     { checked : false,serialNo: 7,publicationNumber: 	'WO2005098476A1', title: 'METHOD AND APPARATUS FOR POSITION ESTIMATION USING REFLECTED LIGHT SOURCES' , dwpiTitle : 'Position estimation system for e.g. mobile autonomous robot, has signal processing unit, provided at e.g. mobile robot, which estimates the position of robot using detected reflection of projected light pattern'},
     { checked : false,serialNo: 8,publicationNumber: 'US20080183497A1', title: 'Method and apparatus for internet-based community of health experts' , dwpiTitle : 'Computer-implemented method for disseminating information e.g. results of MRI, related to particular medical patient, involves providing computer network forum to exchange information among two of patients, physician and one of specialists'},
     { checked : false,serialNo: 9,publicationNumber: 'US20150302571A1', title: 'RECOGNITION-BASED AUTHENTICATION, SYSTEMS AND METHODS' , dwpiTitle : 'Method of initiating handshake between first and second devices involves interpreting image data representative of photo of image presented on first device during handshake session to facilitate communication between devices'},
     { checked : false,serialNo: 10,publicationNumber: 'WO2016013927A1', title: 'A TRANSFORMATIVE ROBOTICS EDUCATION SYSTEM FOR IMPROVING CREATIVITY AMONG PARTICIPANTS' , dwpiTitle : 'Transformative robotics education system for facilitating creativity of participant, has first framework with application of principle of constructivism in assembling robot from robotic kit is initiated to explore constructive material'},
     {checked : false, serialNo: 11,publicationNumber: 'CN2933745Y', title: 'Stair climbing robot' , dwpiTitle : 'Ladder climbing robot has stander, driving mechanism, transmission mechanism, enclasping mechanism, creeping mechanism and control mechanism, where stander is equipped with DC electric motor and gear box, thus provides flexible operation'},
     { checked : false,serialNo: 12,publicationNumber: 'CN2936623Y', title: 'Driving mechanism and driving mechanism of crawling robot' , dwpiTitle : 'Drive mechanism and transmission mechanism of climbing robot'},
     ];
  
  export const roboEdu = [
    { checked : false,serialNo: 1,publicationNumber: 'WO2016013927A1', title: 'A TRANSFORMATIVE ROBOTICS EDUCATION SYSTEM FOR IMPROVING CREATIVITY AMONG PARTICIPANTS' , dwpiTitle : 'Transformative robotics education system for facilitating creativity of participant, has first framework with application of principle of constructivism in assembling robot from robotic kit is initiated to explore constructive material'},
     {checked : false, serialNo: 2,publicationNumber: 'CN2933745Y', title: 'Stair climbing robot' , dwpiTitle : 'Ladder climbing robot has stander, driving mechanism, transmission mechanism, enclasping mechanism, creeping mechanism and control mechanism, where stander is equipped with DC electric motor and gear box, thus provides flexible operation'},
     { checked : false,serialNo: 3,publicationNumber: 'CN2936623Y', title: 'Driving mechanism and driving mechanism of crawling robot' , dwpiTitle : 'Drive mechanism and transmission mechanism of climbing robot'},
     { checked : false,serialNo: 4,publicationNumber: 'CN106600478A', title: 'Multifunctional robot system applied to hotel reception service' , dwpiTitle : 'Hotel concierge service multifunctional robot monitoring system, has moving robot body for judging whether customers transacting check-in service is present, and hotel monitoring system body for reminding user about recording process'},
     {checked : false, serialNo: 5,publicationNumber: 'CN109986575A', title: 'Hotel robot with environment monitoring function' , dwpiTitle : 'Environment monitoring function featured robot for use in hotel, has voltage monitoring device and touch screen whose output ends are connected with end of processing device, where processing device sends transmission signal to terminal'},
     { checked : false,serialNo: 6,publicationNumber: 'JP2000032140A', title: 'ROBOT HOTEL EMPLOYEE USING SPEECH RECOGNITION' , dwpiTitle : 'Automated hotel attendant using speech recognition for coordinating room-to-room calling over a telephone switching system'},
     { checked : false,serialNo: 7,publicationNumber: 	'WO2005098476A1', title: 'METHOD AND APPARATUS FOR POSITION ESTIMATION USING REFLECTED LIGHT SOURCES' , dwpiTitle : 'Position estimation system for e.g. mobile autonomous robot, has signal processing unit, provided at e.g. mobile robot, which estimates the position of robot using detected reflection of projected light pattern'},
     { checked : false,serialNo: 8,publicationNumber: 'US20080183497A1', title: 'Method and apparatus for internet-based community of health experts' , dwpiTitle : 'Computer-implemented method for disseminating information e.g. results of MRI, related to particular medical patient, involves providing computer network forum to exchange information among two of patients, physician and one of specialists'},
     { checked : false,serialNo: 9,publicationNumber: 'US20150302571A1', title: 'RECOGNITION-BASED AUTHENTICATION, SYSTEMS AND METHODS' , dwpiTitle : 'Method of initiating handshake between first and second devices involves interpreting image data representative of photo of image presented on first device during handshake session to facilitate communication between devices'},
     ];
  
  export const roboAI = [
    { checked : false,serialNo: 1,publicationNumber: 'US20200126302A1', title: 'Augmented Reality Platform and Method' , dwpiTitle : 'System for providing complete global mobility, operation and execution, has augmented reality-mixed reality unit for creating live digital twins referred to as hologram projections of all available physical assets including humans'},
     {checked : false, serialNo: 2,publicationNumber: 'FR3052084A1', title: 'SYSTEME POUR LE CONTROLE DE L EVOLUTION D ENGINS TELECOMMANDES' , dwpiTitle : 'Movement control system for remote-controlled vehicle e.g. drone, in public place, has computer for calculating flight parameters, and transmission unit for transmitting flight parameters to corresponding remote-controlled vehicle'},
     { checked : false,serialNo: 3,publicationNumber: 'UA84254C2', title: '	THE MINIMAL PLASMID-BASED SYSTEM FOR GENERATION OF INFECTIOUS NEGATIVE STRANDED RNA OF VIRUSES FROM THE CLONED VIRUS cDNA, THE HOST CELL, CONTAINING THE PLASMID-BASED SYSTEM, THE METHOD FOR PRODUCTION OF INFECTIOUS NEGATIVE STRANDED RNA OF VIRUS AND THE METHOD FOR VACCINATION OF A PERSON AGAINST INFECTION OF NEGATIVE STRANDED RNA VIRUS' , dwpiTitle : '-'},
     { checked : false,serialNo: 4,publicationNumber: 'CN106600478A', title: 'Multifunctional robot system applied to hotel reception service' , dwpiTitle : 'Hotel concierge service multifunctional robot monitoring system, has moving robot body for judging whether customers transacting check-in service is present, and hotel monitoring system body for reminding user about recording process'},
     {checked : false, serialNo: 5,publicationNumber: 'CN109986575A', title: 'Hotel robot with environment monitoring function' , dwpiTitle : 'Environment monitoring function featured robot for use in hotel, has voltage monitoring device and touch screen whose output ends are connected with end of processing device, where processing device sends transmission signal to terminal'},
     { checked : false,serialNo: 6,publicationNumber: 'JP2000032140A', title: 'ROBOT HOTEL EMPLOYEE USING SPEECH RECOGNITION' , dwpiTitle : 'Automated hotel attendant using speech recognition for coordinating room-to-room calling over a telephone switching system'},
     { checked : false,serialNo: 7,publicationNumber: 	'WO2005098476A1', title: 'METHOD AND APPARATUS FOR POSITION ESTIMATION USING REFLECTED LIGHT SOURCES' , dwpiTitle : 'Position estimation system for e.g. mobile autonomous robot, has signal processing unit, provided at e.g. mobile robot, which estimates the position of robot using detected reflection of projected light pattern'},
     { checked : false,serialNo: 8,publicationNumber: 'US20080183497A1', title: 'Method and apparatus for internet-based community of health experts' , dwpiTitle : 'Computer-implemented method for disseminating information e.g. results of MRI, related to particular medical patient, involves providing computer network forum to exchange information among two of patients, physician and one of specialists'},
     { checked : false,serialNo: 9,publicationNumber: 'US20150302571A1', title: 'RECOGNITION-BASED AUTHENTICATION, SYSTEMS AND METHODS' , dwpiTitle : 'Method of initiating handshake between first and second devices involves interpreting image data representative of photo of image presented on first device during handshake session to facilitate communication between devices'},
     ];
  
  export const roboHotel = [
    { checked : false,serialNo: 1,publicationNumber: 'CN106600478A', title: 'Multifunctional robot system applied to hotel reception service' , dwpiTitle : 'Hotel concierge service multifunctional robot monitoring system, has moving robot body for judging whether customers transacting check-in service is present, and hotel monitoring system body for reminding user about recording process'},
     {checked : false, serialNo: 2,publicationNumber: 'CN109986575A', title: 'Hotel robot with environment monitoring function' , dwpiTitle : 'Environment monitoring function featured robot for use in hotel, has voltage monitoring device and touch screen whose output ends are connected with end of processing device, where processing device sends transmission signal to terminal'},
     { checked : false,serialNo: 3,publicationNumber: 'JP2000032140A', title: 'ROBOT HOTEL EMPLOYEE USING SPEECH RECOGNITION' , dwpiTitle : 'Automated hotel attendant using speech recognition for coordinating room-to-room calling over a telephone switching system'},
     { checked : false,serialNo: 4,publicationNumber: 	'WO2005098476A1', title: 'METHOD AND APPARATUS FOR POSITION ESTIMATION USING REFLECTED LIGHT SOURCES' , dwpiTitle : 'Position estimation system for e.g. mobile autonomous robot, has signal processing unit, provided at e.g. mobile robot, which estimates the position of robot using detected reflection of projected light pattern'},
     { checked : false,serialNo: 5,publicationNumber: 'US20080183497A1', title: 'Method and apparatus for internet-based community of health experts' , dwpiTitle : 'Computer-implemented method for disseminating information e.g. results of MRI, related to particular medical patient, involves providing computer network forum to exchange information among two of patients, physician and one of specialists'},
     { checked : false,serialNo: 6,publicationNumber: 'US20150302571A1', title: 'RECOGNITION-BASED AUTHENTICATION, SYSTEMS AND METHODS' , dwpiTitle : 'Method of initiating handshake between first and second devices involves interpreting image data representative of photo of image presented on first device during handshake session to facilitate communication between devices'},
     { checked : false,serialNo: 7,publicationNumber: 'WO2016013927A1', title: 'A TRANSFORMATIVE ROBOTICS EDUCATION SYSTEM FOR IMPROVING CREATIVITY AMONG PARTICIPANTS' , dwpiTitle : 'Transformative robotics education system for facilitating creativity of participant, has first framework with application of principle of constructivism in assembling robot from robotic kit is initiated to explore constructive material'},
     {checked : false, serialNo: 8,publicationNumber: 'CN2933745Y', title: 'Stair climbing robot' , dwpiTitle : 'Ladder climbing robot has stander, driving mechanism, transmission mechanism, enclasping mechanism, creeping mechanism and control mechanism, where stander is equipped with DC electric motor and gear box, thus provides flexible operation'},
     { checked : false,serialNo: 9,publicationNumber: 'CN2936623Y', title: 'Driving mechanism and driving mechanism of crawling robot' , dwpiTitle : 'Drive mechanism and transmission mechanism of climbing robot'},
     { checked : false,serialNo: 10,publicationNumber: 'WO2016013927A1', title: 'A TRANSFORMATIVE ROBOTICS EDUCATION SYSTEM FOR IMPROVING CREATIVITY AMONG PARTICIPANTS' , dwpiTitle : 'Transformative robotics education system for facilitating creativity of participant, has first framework with application of principle of constructivism in assembling robot from robotic kit is initiated to explore constructive material'},
     {checked : false, serialNo: 11,publicationNumber: 'CN2933745Y', title: 'Stair climbing robot' , dwpiTitle : 'Ladder climbing robot has stander, driving mechanism, transmission mechanism, enclasping mechanism, creeping mechanism and control mechanism, where stander is equipped with DC electric motor and gear box, thus provides flexible operation'},
     { checked : false,serialNo: 12,publicationNumber: 'CN2936623Y', title: 'Driving mechanism and driving mechanism of crawling robot' , dwpiTitle : 'Drive mechanism and transmission mechanism of climbing robot'},
   ];